import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { PropsWithChildren } from "react";
import "./globals.css";
import Link from "next/link";
import { NAV_LINKS } from "@/src/config";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }: PropsWithChildren & { modal: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      <div>
        <nav className="inset-0 py-6 grid place-items-center">
          <ul className="flex items-center gap-4">
            {NAV_LINKS.map(link => (
              // Obsługa zdarzenia 'hover'
              <li key={link.id} className="transition-colors hover:text-blue-500">
                <Link href={link.href}>{link.title}</Link>
              </li>
            ))}
          </ul>
        </nav>

        <main className="py-16 max-w-4xl mx-auto">{children}</main>
        {modal}
      </div>
      </body>
    </html>
  );
}
