import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Kablammo } from 'next/font/google'
import { Handjet } from 'next/font/google'

const kablammo = Kablammo({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-kablammo',
})

const handjet = Handjet({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-handjet',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rozdział 3: Komponenty Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${kablammo.variable} ${handjet.variable} $ h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
